package estados;

public enum EstadoAprobacionPedidoCliente {
	IngresadoenSucursal,AprobadoenSucursal,PendienteAceptacionCliente,AceptadoCliente, PendienteAprobarSucursal, RechazadoenSucursal,Completo, EnEsperaFinalizacionOrdendeProduccion;
}
